#!/usr/bin/python3
from sys import argv
def factory(num):
    for i in range(2, num):
        if num % i == 0:
            p = i
            q = int(num // p)
            print(f"{num}={q}*{p}")
            break
    return

def factors(filename):
    """read_file and prints them out"""

    with open(filename, encoding="utf-8") as my_file:
        for i in my_file.readlines():
            n = int(i)
            result = factory(n)


if __name__ == "__main__":
    factors(argv[1])
